/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Expenses } from "./Expenses";
import { ExpensesCountArgs } from "./ExpensesCountArgs";
import { ExpensesFindManyArgs } from "./ExpensesFindManyArgs";
import { ExpensesFindUniqueArgs } from "./ExpensesFindUniqueArgs";
import { DeleteExpensesArgs } from "./DeleteExpensesArgs";
import { ExpensesService } from "../expenses.service";
@graphql.Resolver(() => Expenses)
export class ExpensesResolverBase {
  constructor(protected readonly service: ExpensesService) {}

  async _expensesItemsMeta(
    @graphql.Args() args: ExpensesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Expenses])
  async expensesItems(
    @graphql.Args() args: ExpensesFindManyArgs
  ): Promise<Expenses[]> {
    return this.service.expensesItems(args);
  }

  @graphql.Query(() => Expenses, { nullable: true })
  async expenses(
    @graphql.Args() args: ExpensesFindUniqueArgs
  ): Promise<Expenses | null> {
    const result = await this.service.expenses(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Expenses)
  async deleteExpenses(
    @graphql.Args() args: DeleteExpensesArgs
  ): Promise<Expenses | null> {
    try {
      return await this.service.deleteExpenses(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
